<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap</title>
<style type="text/css">
body{font-family:Arial,sans-serif;font-size:14px;color:#333;background:#f5f5f5;margin:0;padding:20px}
.container{max-width:1200px;margin:0 auto;background:#fff;padding:30px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1)}
h1{color:#667eea;font-size:24px;margin:0 0 10px}
p{color:#666;margin:0 0 20px}
table{width:100%;border-collapse:collapse;margin-top:20px}
th{background:#667eea;color:#fff;padding:12px;text-align:left;font-weight:600}
td{padding:12px;border-bottom:1px solid #eee}
tr:hover{background:#f9f9f9}
a{color:#667eea;text-decoration:none}
a:hover{text-decoration:underline}
.count{color:#999;font-size:13px}
</style>
</head>
<body>
<div class="container">
<h1>XML Sitemap</h1>
<p>This XML Sitemap is generated by BuChat to make your content more visible for search engines.</p>
<p class="count">Number of URLs in this XML Sitemap: <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong></p>
<table>
<tr>
<th>URL</th>
<th>Priority</th>
<th>Change Frequency</th>
</tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="sitemap:priority"/></td>
<td><xsl:value-of select="sitemap:changefreq"/></td>
</tr>
</xsl:for-each>
</table>
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
